### ISSUE TITLE
Rusty Hatch Texture Bug

### ISSUE THREAD

**Issue by AveoCross** [Ordinastie/MalisisDoors#171]
Hi! I have MalisisDoors installed in my private modpack. I crafted and placed Rusty Hatch and noticed that frame is bugged.
Screen: https://a.pomf.cat/uxpogz.png
Frame and ladder is not visible. Relogging into save/server does nothing. But if any block near is updated, frame and ladder appears. But couple od seconds later disappears again.

MalisisCore 4.4.0
MalisisDoors 5.2.0
Minecraft 1.10.2
Latest Forge

**Comment by Niko-sk2x** [comment]
I remember getting the same issue, I may still have a world that reproduces it if needed.

**Comment by Ordinastie** [comment]
I was never able to replicate, so if you have a world where it happens reliably, then yes, I'd like to see it.

**Comment by Niko-sk2x** [comment]
I noticed that it happened with any world with my small modpack. After some testing, I found the source of the issue to be OptiFine.

I tested it with these versions (latest 1.11.2 versions at the time I created this private pack):
 * Forge 1.11.2-13.20.0.2345
 * malisiscore 1.11.2-5.2.1
 * malisisdoors 1.11.2-6.1.1
 * OptiFine 1.11.2 HD U C2

I also tested with various video settings to make sure it's not caused by something like fast renderer.

**Comment by AveoCross** [comment]
I don't have OptiFine in my Modpack. But I have FoamFix Anarchy and BetterFPS. I gonna test this without these in client.

**Comment by AveoCross** [comment]
Nope. Even without BetterFPS and FoamFix I am still experiencing this.
http://aveocross.ml/uploads/hatch_bug.gif

**Comment by AveoCross** [comment]
Okay... I just found next bug with hatch.
I tried to destroy Hatch with a pickaxe and texture disappeared for a second, item dropped, I took the item and suddenly hatch appeared again. I tried to destroy it, texture disappeared, second item dropped but ghost blocks still exists on world and drops Rusty Hatch as a item but they can't be destroyed permanently.
Same versions as before.
https://a.pomf.cat/ecxvhy.png

I can provide my save and modpack to test it if needed.
EDIT: No, I can't provide save because I'm stupid and destroyed these ghost blocks in creative... But if is any chance to help with reproducing that bug, I can send you that files anyway c:

**Comment by Ordinastie** [comment]
Breaking Rusty Hatch has been fixed in MalisisCore 1.12.2-6.3.0.

**Comment by GamerXDF** [comment]
> Breaking Rusty Hatch has been fixed in MalisisCore 1.12.2-6.3.0.

I still have this bug (
![image](https://user-images.githubusercontent.com/68789690/88464548-67497280-cec4-11ea-9c4f-286e3a060d35.png)

**Comment by wllp** [comment]
I just experienced this bug as well

**Comment by feoranis26** [comment]
Same in ATM 3

**Comment by KittenPixel** [comment]
Me to
![image](https://user-images.githubusercontent.com/79544605/236330901-465d3c04-4458-44a8-960c-afa31e7ddd25.png)
I have matter overdrive but this worked before with matter overdrive

**Comment by KenyMylankca** [comment]
anyone knows how to fix this? also rusty ladder have no textures in my game, very glitchy
