### ISSUE TITLE
Can't Compile Doors -> DoorFactoryTileEntity constructor error

### ISSUE THREAD

**Issue by Dockter** [Ordinastie/MalisisDoors#205]
Error:  http://www.almuramc.com/images/DoorsCompileError.png

**Comment by Ordinastie** [comment]
We've been over this. You need to make sure MalisisCore is accessible. You need to edit build.gradle to download it from Maven.

**Comment by Dockter** [comment]
This has nothing to do with MalisisCore being able to be seen.  If MC couldn't be seen I would have thousands of errors.

See this commit: https://github.com/AlmuraDev/MalisisDoors/commit/e0225f0ba2b0f611c2df790f00fefc12df01ddfb

**Comment by Dockter** [comment]
That is what I had to do to get gradle and IntelliJ from complaining about the constructor error.

**Comment by Dockter** [comment]
Also had to do this to fix a TE issue:

https://github.com/AlmuraDev/MalisisDoors/commit/a8237481c9960859710f0e889a0655ef65f3c4cc

**Comment by Ordinastie** [comment]
The method was clearly already implemented in IDirectInventoryProvider. I would say there is something wrong with your setup.

The TE NPE is already fixed in  d073549.

**Comment by Dockter** [comment]
This is not resolved.  Reproduce able with clean clone, gradlew build, or inside of IntelliJ.
