### ISSUE TITLE
forcefield doors sometimes crash client

### ISSUE THREAD

**Issue by hunter688** [Ordinastie/MalisisDoors#24]
http://pastebin.com/7Ep6zD4f

http://pastebin.com/Uvu7xG9K

**Comment by hunter688** [comment]
Is this fixed in the new version?

**Comment by Ordinastie** [comment]
I think something made the TE invalid in world and should be removed via third party program.
Reopen if issue still happens.
